---
# tasks file for network
- name: "Disable cloud-init"
  become: true
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: cloud-init

- name: "Delete old netplan config"
  become: true
  ansible.builtin.file:
    state: absent
    path: "/etc/netplan/*"

- name: "Configure netplan"
  become: true
  ansible.builtin.template:
    src: "ifconfig.j2"
    dest: "/etc/netplan/00-netplan-custom.yaml"
    owner: root
    group: root
    mode: '0644'

- name: "Apply new netplan config"
  become: true
  ansible.builtin.shell:
    cmd: "netplan apply"
  ignore_errors: "{{ ansible_check_mode }}"
  async: 45
  poll: 0

- name: "Annonce"  
  ansible.builtin.debug:
    msg:
      "Interface {{ ifaceName }} changed.
      His IP is: {{ ansible_facts.default_ipv4.address }},
      Netmask: {{ ansible_facts.default_ipv4.netmask }},
      Gateway: {{ ansible_facts.default_ipv4.gateway }},
      MAC-Address: {{ ansible_facts.default_ipv4.macaddress }}"