---
# tasks file for grub
- name: "Configure grub default cmdline"
  become: true
  ansible.builtin.lineinfile:
    state: present
    backrefs: true
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
    line: '\1 intel_idle.max_cstate=0"'

- name: "Rebuild grub"
  ansible.builtin.shell: update-grub2