---
# tasks file for dm-crypt
# Install cryptsetup package
# - name: Install cryptsetup
#   become: true
#   ansible.builtin.apt:
#     name: cryptsetup
#     state: present
#     update_cache: true
#   tags: install